[Paths]
source_dir = C:\remoteCode
destination_dir = C:\Users\Administrator\Desktop\交接资料\项目代码

[Exclusions]
# 使用逗号分隔要排除的文件夹名称
excluded_dirs = .git,.gitee, __pycache__, node_modules, venv,rerank-api,Verba,Chatterbox-TTS-Server,.idea

# 使用逗号分隔要排除的文件后缀
excluded_extensions = .log, .tmp, .bak
